/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        outline: "#8d90a0",
        "on-surface-variant": "#c3c6d6",
        "on-primary-container": "#c4d2ff",
        "inverse-on-surface": "#233143",
        tertiary: "#bcc7de",
        "on-surface": "#d4e4fa",
        "on-tertiary": "#263143",
        "surface-container": "#122131",
        "on-tertiary-fixed-variant": "#3c475a",
        "secondary-container": "#414a55",
        "on-primary-fixed-variant": "#0040a2",
        "on-secondary-container": "#b0b9c7",
        "surface-variant": "#273647",
        "tertiary-fixed-dim": "#bcc7de",
        "tertiary-fixed": "#d8e3fb",
        background: "#051424",
        error: "#ffb4ab",
        "on-tertiary-container": "#c8d3eb",
        "error-container": "#93000a",
        "inverse-surface": "#d4e4fa",
        "secondary-fixed-dim": "#bec7d5",
        "primary-fixed": "#dae2ff",
        "surface-tint": "#b2c5ff",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#0c56d0",
        "surface-container-low": "#0d1c2d",
        "on-tertiary-fixed": "#111c2d",
        "on-secondary": "#28313c",
        "surface-container-lowest": "#010f1f",
        "tertiary-container": "#505b6f",
        "on-secondary-fixed": "#131c26",
        surface: "#051424",
        "on-secondary-fixed-variant": "#3f4853",
        "on-primary": "#002b73",
        secondary: "#bec7d5",
        "outline-variant": "#434654",
        "surface-container-highest": "#273647",
        "secondary-fixed": "#dae3f1",
        "surface-bright": "#2c3a4c",
        "on-background": "#d4e4fa",
        "surface-dim": "#051424",
        "primary-container": "#0052cc",
        primary: "#b2c5ff",
        "on-primary-fixed": "#001848",
        "on-error": "#690005",
        "surface-container-high": "#1c2b3c",
        "primary-fixed-dim": "#b2c5ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "row-height-compact": "32px",
        gutter: "16px",
        unit: "4px",
        "row-height-standard": "44px",
        "container-padding": "24px",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};